version: "3.9"

services:
    api:
        container_name: api
        build: .
        ports:
            - 3000:3000
        environment:
            - DB_HOST=db
            - DB_PASSWORD=1234
            - DB=m6
            - DB_USER=kenzinho
            - SECRET_KEY=71c70d08e0e6784609deef03608acb10924ee1d930c02219b7cb9c12defffb61
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .:/app

    db:
        container_name: db
        image: postgres:14
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=kenzinho
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=m6
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U kenzinho -d m6"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s
